### PR TITLE
[fix] (all) fix ignores

### PR DESCRIPTION
**Pull request by dzdidi**
delete tracked files from git's cached (dist and docs)
Reduce size of `./packages` from 31M to 2.8M

### CODE REVIEW

**Comment by dylanseago** [comment]
Tracking build artifacts was intentional. But it was a decision I was on the fence about and I'm more than happy to stop. I think the reasons behind it were
1. We've always done it that way
2. It makes it possible to install from git (`npm install go-faast/coin-payments`)
3. I don't remember any others, but we should probably stop committing artifacts

We'll also need to modify the `postversion` scripts in package.json because it'll add these back

**Comment by dzdidi** [comment]
> Tracking build artifacts was intentional. But it was a decision I was on the fence about and I'm more than happy to stop. I think the reasons behind it were

**Comment by dylanseago** [comment]
I agree. I'm all for this change.

Current npm scripts for releasing will need to be adjusted for this change. Each package has a `version` script that runs `npm run build && git add -Af dist docs` which is going to add all these files back if not removed. Additionally, `lerna run build` will need to be added to the "Steps to publish" section of the readme to ensure the artifacts are generated before being published to npm. Consolidating all that into a single script would be a good idea.

**Comment by dylanseago** [comment]
Changes addressed in v2.2.1

**Pull request closed without merging**
