### PR TITLE
Standardize getBalance behaviour for unused addresses

### PR DESCRIPTION
**Pull request by dylanseago**
Currently calling `getBalance` on an unused address will either return a zero balance (BTC, ETH, TRX) or throw an error (XRP, XLM). This PR makes all coins return zero balances when an address is unused.

Summary of changes to `getBalance` result:
- Adjust `confirmedBalance` to no longer deduct the minimum balance and better reflect what it's name implies
- Add `spendableBalance` to convey how much can actually be spent. (ie `confirmedBalance + unconfirmedBalance - minBalance`)
- Add `unactivated` flag to indicate that an address has not yet received the minimum balance needed to be activated (XRP and XLM)

### CODE REVIEW

**Comment by dzdidi** [comment]
@dylanseago ,  I don't know what do you mean by 'unused address', is it the same as `unactivated: true`?

**Comment by dzdidi** [comment]
I would encourage to use `activated: false` instead of `unactivated: true` , there are plenty of studies which prove that negations are harder to process for human mind.

**Comment by dzdidi** [comment]
other than that look good 🥇

**Comment by moeadham** [comment]
+1 for activated = false

Le mer. 29 avr. 2020 à 11:56, Denys Zaliskyi <notifications@github.com> a
écrit :

**Comment by dylanseago** [comment]
Thanks for the feedback. I agree with avoiding negations, I'll try to explain my reasoning.

An "activated" address means it's been sent the minimum balance and is now useable. XLM and XRP documentation both refer to this concept with the same terminology. An "unused" address is a valid address that's never seen a transaction, it's not on the blockchain/ledger at all. An unused XRP/XLM address is therefore not activated, but the converse is not necessarily true. For BTC/ETH/TRX there's no activation concept, and querying the network for an unused address simply returns a zero balance.

My question is, if I switch naming, what should the value of `activated` be for BTC/ETH/TRX addresses? Currently I return `unactivated=false` because I think that still somewhat makes sense, since they can never be unactivated. It also makes the flag convenient for the use case we're targeting: checking for unactivated addresses.

```js
if (balance.unactivated) {
  throw new Error('gotta fund your address!')
}
```

Here's my thoughts on each option:
1. `activated=true` - Doesn't conceptually make sense because a BTC address can't be "activated", however would be convenient for our use case
```js
if (!balance.activated) {
  throw new Error('gotta fund your address')
}
```
2. `activated=false` - Makes sense conceptually, but now reduces the usability of the flag since the behaviour is inconsistent across coins
```js
if (!balance.activated && (coin === 'XRP' || coin === 'XLM')) {
  throw new Error('gotta fund your address')
}
```
3. `activated=undefined` - Possibly makes the most sense? However reduces the convenience of the flag slightly because now you have to explicitly check for `false` instead of coercing it into a boolean - an easily overlooked mistake.
```js
if (balance.activated === false) {
  throw new Error('gotta fund your address')
}
```
4. Rename `unactivated` to something else that doesn't use a negation, such as `requiresActivation`. Open to suggestions.

I'm open to both options 1 and 3, but my preference is towards option 4. Let me know your thoughts.

**Comment by moeadham** [comment]
@dylanseago #4 makes perfect sense to me.

**Comment by dzdidi** [comment]
> Doesn't conceptually make sense because a BTC address can't be "activated", however would be convenient for our use case

**Pull request merged**
